### PR TITLE
Support TRIZ method

### PR DESCRIPTION
**Pull request by gaobrian**
Catch up latest

### CODE REVIEW

**Comment by Joeran** [comment]
@gaobrian can you explain what your new code is doing?

**Comment by koppor** [comment]
The contribution includes the source of the [Fast JSON Processor](https://github.com/alibaba/fastjson). It should be included as binary via Apache Ivy.

**Comment by buhtz** [comment]
I would recommend to close that PR without merging.

There is not enough information provided.

There is only one (definitly to big!) commit in that PR.

And it is to old (7 month) without any activity.

**Comment by evolve2k** [comment]
The PR attempts to rebrand the logo with the term "Trizable" as well as includes a bunch of code from alibaba. Not passing the smell test for me. I would recommend this PR is rejected and the author can defend it and reopen a smaller PR if they so desire.

Recommend close now. Better not to risk having someone accidentally merge this.

**Pull request closed without merging**
